trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  - task: AwsCLI@1
    inputs:
      awsServiceEndpoint: 'AWS_Service_Connection_Name'
      regionName: 'us-east-1'  # Specify your AWS region
      command: 's3 ls'  # Example command to list S3 buckets

  - script: terraform init
    displayName: 'Terraform Init'

  - script: terraform plan
    displayName: 'Terraform Plan'

  - script: terraform apply -auto-approve
    displayName: 'Terraform Apply'
