trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Clone the GitHub repository
  - checkout: self
    persistCredentials: true

  - script: |
      git clone https://github.com/Gowtham1906/terraform-infra-deployment.git
    displayName: 'Clone Git Repository'

  # Navigate to the directory and initialize Terraform
  - script: |
      cd terraform-infra-deployment/terraform-s3/main.tf
      terraform init
    displayName: 'Terraform Init'

  # Navigate to the directory and plan Terraform
  - script: |
      cd terraform-infra-deployment/terraform-s3/main.tf
      terraform plan
    displayName: 'Terraform Plan'

  # Navigate to the directory and apply Terraform
  - script: |
      cd terraform-infra-deployment/terraform-s3
      terraform apply -auto-approve
    displayName: 'Terraform Apply'

