trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Clone the GitHub repository and initialize Terraform, plan, and apply in one script
  - checkout: self
    persistCredentials: true

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  - script: |
      git clone https://github.com/Gowtham1906/terraform-infra-deployment.git
      cd terraform-infra-deployment/terraform-s3
      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Clone Git Repo, Terraform Init, Plan, and Apply'
  
  # # Send email notification on failure
  # - task: Email@1
  #   condition: failed()
  #   inputs:
  #     to: 'gowthamsamaraj@gmail.com'
  #     subject: 'Azure DevOps Pipeline Failed'
  #     body: 'The pipeline failed during the Terraform deployment.'
  - task: SendEmail@1
    inputs:
      To: 'gowthamsamaraj@gmail.com'
      From: 'gowthamsamaraj@gamil.com'
      Subject: 'Failed Pipeline'
      BodyAsHtml: false
      AddAttachment: false
      SmtpServer: 'smtp.gmail.com'
      SmtpPort: '465'

