trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # AWS credentials will be securely stored in the pipeline settings
  AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
  AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

steps:
  # Checkout code
  - checkout: self
    persistCredentials: true

  # Install Terraform
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'

  # Export AWS credentials as environment variables and run Terraform
  - script: |
      export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
      export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
      git clone https://github.com/Gowtham1906/terraform-infra-deployment.git
      cd terraform-infra-deployment/terraform-s3
      terraform init
      terraform plan
      terraform apply -auto-approve
    displayName: 'Clone Git Repo, Terraform Init, Plan, and Apply'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
