trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.0'


  - task: AWSCLI@1
    inputs:
      awsCredentials: 'AWSServiceConnection'
      regionName: 'us-east-1'
      awsCommand: 's3'
      awsSubCommand: 'ls'

  - script: terraform init
    displayName: 'Terraform Init'

  - script: terraform plan
    displayName: 'Terraform Plan'

  - script: terraform apply -auto-approve
    displayName: 'Terraform Apply'
